### ISSUE TITLE
Develop derived table po_purchase_orders_acq_unit_ids

### ISSUE THREAD

**Issue by sbeltaine** [folio-org/folio-analytics#134] opened 2020-10-22 15:04 UTC
This derived table was pushed to folio/analytics by Nancy Bolduc and needs to be reviewed and merged into the repository.

**Comment by nassibnassar** [comment] 2020-10-22 15:22
I don't see a pull request for this.

**Comment by nassibnassar** [comment] 2020-10-22 15:24
This appears to be a duplicate of issue #95

**Closed** 2020-10-22 15:27 UTC
Labels: duplicate
